language: node_js  #设置语言
node_js: stable  #设置相应的版本

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

before_install:
    - export TZ='Asia/Shanghai' # 更改时区

install:
  - npm install  #安装hexo及插件

before_script:
 - npm install -g gulp

script:
  - hexo clean  #清除
  - hexo g && gulp  #生成

after_script:
  - cd ./public
  - git init
  - git config user.name "FormatToday"
  - git config user.email "616099456@qq.com"
  - git add .
  - git commit -m "更新博客"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - backup
env:
 global:
   - GH_REF: github.com/FormatToday/FormatToday.github.io.git

notifications:
  email:
    - 616099456@qq.com
  on_success: change
  on_failure: always