# Hexo 配置文件
## 文档: https://hexo.io/docs/configuration.html
## 源码: https://github.com/hexojs/hexo/

# 站点
title: 讲不错哦
subtitle: 我认真的
description: 这里没有描述
keywords: blog
author: 章钦
language: zh-Hans
timezone: Asia/Shanghai

# URL
## 如果网站被放置在子目录中, 把 url 设置成 'http://yoursite.com/child' 并且把 root 设置成 '/child/'
url: http://zhangqin56.cn
root: /
# 博客文章的 URL 结构
permalink: :category/:year/:month/:day/:title.html
permalink_defaults:

# 目录
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# 写作
new_post_name: :title.md # 新文章的文件名
default_layout: post
titlecase: true # 把标题转换为标准格式（大小写）
external_link: true # 在新选项卡中打开外部链接
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
# 代码高亮设置
highlight:
  enable: true
  line_number: false
  # 代码自动高亮
  auto_detect: false
  tab_replace:
  
# 主页设置
# path: 博客首页的根路径。 (默认 = '')
# per_page: 每页文章。 (0 = 取消分页)
# order_by: 文章顺序。 (默认按日期递减的顺序)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# 分类 & 标签
default_category: uncategorized
# URL 中的分类和标签“翻译”成英文
# 见：https://github.com/hexojs/hexo/issues/1162
category_map:
tag_map:

# 日期 / 时间 格式
## Hexo 使用 Moment.js 来转换和显示时间
## 可以按下面网址的定义自定义日期格式
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# 分页
## 设置 0 取消分页
per_page: 10
pagination_dir: page

# 扩展
## 插件: https://hexo.io/plugins/
## 主题: https://hexo.io/themes/

# RSS，要先进入站点文件夹根目录安装插件
# npm install hexo-generator-feed --save 即可
# 无需更多配置
# 参数说明查看 README：https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom
  path: atom.xml
# 文章数，0 为全部
  limit: 0
  hub:
  # 是否包含文章内容
  content: true
  
# emoji 支持
githubEmojis:
  enable: true
  idName: github-emoji
  unicode: false
  styles:
  localEmojis: 
# theme: landscape
theme: next

# 部署
## 文档: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/FormatToday/FormatToday.github.io.git
  branch: master
